compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: NO # MULTI_GPU, NO, FSDP
downcast_bf16: 'no'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: 172.17.0.7
main_process_port: 8005
main_training_function: main
mixed_precision: fp16 # fp16, no
num_machines: 1
num_processes: 1 #4
rdzv_backend: static
same_network: true
use_cpu: false
